// Deterministic stand-in provider (Phase 4A). Makes no network calls, reads
// no media bytes and performs no analysis: it returns clearly labelled
// placeholder output that passes report validation, so the queue, leases,
// versioning and storage can be exercised end to end.
//
// Failure modes can be injected for tests.
import type { ServiceAiProvider, SynthesisRequest } from "./provider";
import { ServiceAiProviderError } from "./provider";
import { PRODUCT_IDS, type ServiceCallReportContent } from "./report-schema";
import type { ServiceProductId } from "../types";

export const STUB_PROVIDER_ID = "stub";

export interface StubOptions {
  /** Media ids whose transcription fails. */
  failMedia?: Record<string, { code: string; retryable: boolean }>;
  /** Photo labels ("Photo 1") whose observation fails (the photo stage never sees media ids). */
  failPhotos?: Record<string, { code: string; retryable: boolean }>;
  /** Custom po-1 output per photo call (label, call number); default: one hedged NOTHING_NOTABLE_VISIBLE. */
  photoContent?: (label: string, call: number) => unknown;
  /** Synthesis behaviour per call, in order (then "ok"). */
  synthesis?: ("ok" | "malformed" | "forbidden" | "unavailable" | "bad_quote" | "incomplete")[];
}

const STUB_NOTE = "Generated by the Phase 4A stub provider: no AI analysis was performed.";

export function createStubServiceAiProvider(options: StubOptions = {}): ServiceAiProvider & { calls: Record<string, number> } {
  const calls = { transcribe: 0, observe: 0, synthesise: 0 };
  const synthesis = [...(options.synthesis ?? [])];
  const failFor = (mediaId: string) => {
    const f = options.failMedia?.[mediaId];
    if (f) throw new ServiceAiProviderError(f.code, f.retryable);
  };

  return {
    id: STUB_PROVIDER_ID,
    capabilities: { transcribe: true, observe: true, synthesise: true },
    models: { transcribe: "stub-transcribe-1", vision: "stub-vision-1", report: "stub-report-1" },
    promptVersions: { transcribe: "stub-1", observe: "stub-1", report: "stub-1" },
    calls,

    async transcribe({ mediaId }) {
      calls.transcribe++;
      failFor(mediaId);
      return { text: "[Stub transcript — no speech recognition was performed.]", language: null, usage: { stubCalls: 1 } };
    },

    async observePhoto({ label }) {
      calls.observe++;
      const f = options.failPhotos?.[label];
      if (f) throw new ServiceAiProviderError(f.code, f.retryable);
      const content = options.photoContent?.(label, calls.observe) ?? {
        photo: { quality: "CLEAR", qualityIssues: [], relevance: "UNCLEAR", visibleProductTypes: [], visibleTextPresent: false, personalInfoVisible: false },
        observations: [{ type: "NOTHING_NOTABLE_VISIBLE", observation: "Placeholder: no image analysis was performed, so nothing may be inferred from this photo.", certainty: "UNCERTAIN", location: null }],
        cannotDetermine: ["Anything about this photo (stub provider)."],
      };
      return { content, usage: { stubCalls: 1 } };
    },

    async synthesiseReport(request) {
      calls.synthesise++;
      const mode = synthesis.shift() ?? "ok";
      if (mode === "unavailable") throw new ServiceAiProviderError("provider_unavailable", true);
      if (mode === "incomplete") return { content: null, usage: { stubCalls: 1 }, outputIssue: "incomplete_output" as const };
      const content = stubContent(request);
      if (mode === "bad_quote" && content.customerReported.statements[0]) content.customerReported.statements[0].quote = "words the customer never said";
      if (mode === "malformed") return { content: { ...content, urgency: { level: "SEVERE" } }, usage: { stubCalls: 1 } };
      if (mode === "forbidden") return { content: { ...content, issueSummary: "We will repair the door free of charge; it is covered by the warranty." }, usage: { stubCalls: 1 } };
      return { content, usage: { stubCalls: 1 } };
    },
  };
}

function stubContent({ input }: SynthesisRequest): ServiceCallReportContent {
  const statements = [
    ...(input.request.description.trim()
      ? [{ id: "st-1", text: truncate(input.request.description.trim(), 300), quote: excerpt(input.request.description), source: { type: "DESCRIPTION" as const, mediaId: null } }]
      : []),
    // Voice notes with no recognised speech have nothing to quote.
    ...input.transcripts.filter((t) => t.text.trim()).map((t, i) => ({
      id: `st-${i + 2}`,
      text: truncate(t.text, 300),
      quote: excerpt(t.text),
      source: { type: t.kind === "VOICE_NOTE" ? ("VOICE_NOTE" as const) : ("VIDEO_AUDIO" as const), mediaId: t.mediaId },
    })),
  ];
  return {
    issueSummary: "[STUB] Placeholder report — no AI analysis was performed.",
    customerReported: { statements, reportedSymptoms: [], reportedOnset: null, locationInProperty: null },
    // scr-1.2: observations are inserted by the server; the model returns none.
    mediaObservations: [],
    unknownsRequiringInspection: [
      { topic: "COMPONENT_FAILURE", question: "Which component, if any, is at fault.", whyUnknown: "Not assessed by the stub provider." },
    ],
    affectedProducts: input.request.productCategories
      .filter((c): c is ServiceProductId => (PRODUCT_IDS as readonly string[]).includes(c))
      .map((category) => ({ category, basis: "CUSTOMER_SELECTED" as const })),
    potentialIssueCategories: [],
    urgency: { level: "NORMAL", indicators: [], reason: "Not assessed: stub provider. Staff should assess urgency from the submission." },
    inspection: { recommended: true, reason: "Not assessed: stub provider." },
    recommendedNextStep: "STAFF_CALLBACK",
    moreInformationNeeded: [],
    confidence: { overall: "LOW", reason: "Placeholder output without analysis." },
    limitations: [STUB_NOTE],
  };
}

const truncate = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
/** A verbatim excerpt (first 200 characters) — always a substring of the source. */
const excerpt = (s: string) => Array.from(s.trim()).slice(0, 200).join("");
