// Service & Aftercare — HTTP contract between the browser and the API.
//
// Plain JSON shapes with no framework or vendor types, shared by the browser
// client (http-client.ts) and the route handler, and documented in
// docs/service-aftercare/API.md so the same contract can be implemented on
// another stack.
import type { ServiceMediaKind, ServiceMediaSource, ServiceProductId, ServiceRequestDraft, ServiceStatus } from "./types";

export const SERVICE_REQUESTS_ENDPOINT = "/api/service-requests";
export const IDEMPOTENCY_HEADER = "Idempotency-Key";

/** Body of POST /api/service-requests. Media itself is not sent (Phase 3). */
export interface CreateServiceRequestPayload {
  customer: {
    fullName: string;
    countryCode: string;
    mobile: string;
    email: string;
    location: string;
    isExistingCustomer: boolean | null;
    reference: string;
  };
  productIds: ServiceProductId[];
  otherProduct: string;
  description: string;
  /** What the customer attached in the browser, so staff know to ask for it. */
  declaredMedia: { photos: number; videos: number; voiceNote: boolean };
}

/** 201 Created (new) or 200 OK (same Idempotency-Key seen before). */
export interface CreateServiceRequestResponse {
  id: string;
  reference: string;
  status: ServiceStatus;
  submittedAt: string;
  /** True when this key had already created the request. */
  replayed: boolean;
  /**
   * Proof that this browser created the request, for the media endpoints.
   * Sent back as `Authorization: Bearer <token>`. A new token is issued on
   * every successful call (including replays) and the previous one stops
   * working. The reference alone never authorises anything.
   */
  upload: { token: string; expiresAt: string };
}

export type ServiceRequestErrorCode =
  | "unauthorised"
  | "upload_authorisation_expired"
  | "media_limit_reached"
  | "media_not_found"
  | "not_uploaded"
  | "media_rejected"
  | "missing_idempotency_key"
  | "unsupported_media_type"
  | "payload_too_large"
  | "invalid_json"
  | "validation_failed"
  | "not_configured"
  | "server_error";

export interface ServiceRequestErrorResponse {
  error: ServiceRequestErrorCode;
  message: string;
  /** Present for validation_failed: field path → message. */
  fields?: Record<string, string>;
}

/** Builds the request body from the wizard's draft. */
export function toCreatePayload(draft: ServiceRequestDraft): CreateServiceRequestPayload {
  const photos = draft.media.filter((m) => m.kind === "photo").length;
  return {
    customer: {
      fullName: draft.customer.fullName.trim(),
      countryCode: draft.customer.countryCode,
      mobile: draft.customer.mobile.trim(),
      email: draft.customer.email.trim(),
      location: draft.customer.location.trim(),
      isExistingCustomer: draft.customer.isExistingCustomer,
      reference: draft.customer.reference.trim(),
    },
    productIds: draft.productIds,
    otherProduct: draft.productIds.includes("other") ? draft.otherProduct.trim() : "",
    description: draft.description.trim(),
    declaredMedia: {
      photos,
      videos: draft.media.length - photos,
      voiceNote: draft.voiceNote !== null,
    },
  };
}

// ─── Media (Phase 3) ─────────────────────────────────────────────────────────
// Files go straight from the browser to private storage via a signed upload
// URL; these endpoints only authorise, verify and remove. See MEDIA.md.

export const mediaEndpoint = (reference: string) => `${SERVICE_REQUESTS_ENDPOINT}/${encodeURIComponent(reference)}/media`;

export type MediaUploadStatus = "PENDING" | "UPLOADED" | "FAILED";

/** Body of POST /api/service-requests/:reference/media — one file. */
export interface AuthoriseMediaPayload {
  /** Generated by the browser per file; repeat it to retry without duplicating. */
  clientMediaId: string;
  kind: ServiceMediaKind;
  mimeType: string;
  size: number;
  fileName: string;
  source: ServiceMediaSource;
  durationSeconds?: number | null;
}

export interface MediaSummary {
  id: string;
  clientMediaId: string;
  kind: ServiceMediaKind;
  mimeType: string;
  fileName: string | null;
  size: number;
  uploadStatus: MediaUploadStatus;
  /** Why verification failed (empty_file, file_too_large, content_does_not_match_type). */
  failureReason: string | null;
}

/** 200 for a new or repeated clientMediaId (same row either way). `upload` is null when the file is already UPLOADED. */
export interface AuthoriseMediaResponse {
  media: MediaSummary;
  upload: { url: string; method: "PUT"; headers: Record<string, string>; expiresInSeconds: number } | null;
}

/** POST …/media/:id/complete → 200 when verified. */
export interface CompleteMediaResponse {
  media: MediaSummary;
}
