-- Service & Aftercare — Phase 3: media evidence (photos, videos, voice notes).
--
-- Files live in the PRIVATE Supabase Storage bucket `service-evidence`; this
-- table records each file and its upload state. Browsers upload directly to
-- Storage with a short-lived signed upload URL issued by the API, after
-- proving (with a per-request upload token) that they created the request.
-- See docs/service-aftercare/MEDIA.md.

-- ─── Upload authorisation on the request ────────────────────────────────────
-- The API returns a random upload token to the browser that created the
-- request and stores only its SHA-256 hash here. A service reference alone
-- (sequential, guessable) never authorises anything.
alter table public.service_requests
  add column upload_token_hash        text,
  add column upload_token_expires_at  timestamptz;

create unique index service_requests_upload_token_hash_key
  on public.service_requests (upload_token_hash) where upload_token_hash is not null;

comment on column public.service_requests.declared_media is
  'Snapshot of what the customer said they attached when submitting. NOT the record of uploaded evidence: service_media rows with upload_status = UPLOADED are authoritative.';

-- ─── Media ──────────────────────────────────────────────────────────────────
create type public.service_media_type as enum ('PHOTO', 'VIDEO', 'VOICE');

-- PENDING  = upload authorised, file not yet verified in storage
-- UPLOADED = file verified in storage (type sniffed, size checked)
-- FAILED   = verification failed; the object has been deleted
-- Removed files are deleted outright (row and object), not kept as a state.
create type public.service_media_upload_status as enum ('PENDING', 'UPLOADED', 'FAILED');

-- Shared by later processing steps (transcription, AI analysis).
create type public.service_media_processing_status as enum
  ('NOT_STARTED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED');

create table public.service_media (
  id                   uuid primary key default gen_random_uuid(),
  service_request_id   uuid not null references public.service_requests (id) on delete cascade,
  -- Generated by the browser per file; makes authorisation idempotent
  -- (double clicks, retries) without creating a second row or object.
  client_media_id      uuid not null,

  media_type           public.service_media_type not null,
  mime_type            text not null,
  file_extension       text not null,
  original_filename    text,                     -- metadata only; never used as a storage key
  source               text check (source in ('camera', 'upload', 'recording')),
  declared_size        bigint not null check (declared_size > 0),
  file_size            bigint,                   -- verified size of the stored object

  storage_bucket       text not null default 'service-evidence',
  storage_path         text not null unique,     -- service-requests/<year>/<reference>/<id>.<ext>
  upload_status        public.service_media_upload_status not null default 'PENDING',
  failure_reason       text,
  uploaded_at          timestamptz,

  -- Filled by later phases; the original object is never modified.
  duration_seconds     numeric(8, 2),
  width                integer,
  height               integer,
  transcript           text,
  transcript_status    public.service_media_processing_status not null default 'NOT_STARTED',
  ai_analysis          jsonb,
  ai_analysis_status   public.service_media_processing_status not null default 'NOT_STARTED',

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  unique (service_request_id, client_media_id)
);
create index service_media_request_idx on public.service_media (service_request_id, created_at);
create index service_media_stale_idx on public.service_media (upload_status, updated_at) where upload_status <> 'UPLOADED';

create trigger service_media_touch before update on public.service_media
  for each row execute function public.touch_updated_at();

alter table public.service_media enable row level security;
revoke all on public.service_media from anon, authenticated;

-- ─── reserve_service_media ──────────────────────────────────────────────────
-- Registers one file for upload (or returns the existing row for the same
-- client_media_id). Locks the request row so concurrent calls can't exceed the
-- per-request limits. A FAILED row is reset to PENDING for a retry; its
-- storage path is kept, so a retry never creates a second object.
create function public.reserve_service_media(
  p_request_id       uuid,
  p_client_media_id  uuid,
  p_media_type       public.service_media_type,
  p_mime_type        text,
  p_extension        text,
  p_declared_size    bigint,
  p_original_name    text,
  p_source           text,
  p_duration         numeric,
  p_max_visual       integer,
  p_max_voice        integer
) returns setof public.service_media
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request  public.service_requests%rowtype;
  v_existing public.service_media%rowtype;
  v_active   integer;
  v_id       uuid := gen_random_uuid();
begin
  select * into v_request from public.service_requests where id = p_request_id for update;
  if not found then
    raise exception 'service_request_not_found' using errcode = 'P0002';
  end if;

  select * into v_existing from public.service_media
   where service_request_id = p_request_id and client_media_id = p_client_media_id;
  if found then
    if v_existing.upload_status = 'FAILED' then
      update public.service_media
         set upload_status = 'PENDING', failure_reason = null, file_size = null,
             mime_type = p_mime_type, declared_size = p_declared_size
       where id = v_existing.id
       returning * into v_existing;
    end if;
    return next v_existing;
    return;
  end if;

  select count(*) into v_active from public.service_media
   where service_request_id = p_request_id
     and upload_status <> 'FAILED'
     and (case when p_media_type = 'VOICE' then media_type = 'VOICE' else media_type <> 'VOICE' end);
  if v_active >= (case when p_media_type = 'VOICE' then p_max_voice else p_max_visual end) then
    raise exception 'media_limit_reached' using errcode = 'P0001';
  end if;

  return query
  insert into public.service_media (
    id, service_request_id, client_media_id, media_type, mime_type, file_extension,
    original_filename, source, declared_size, duration_seconds, storage_path
  ) values (
    v_id, p_request_id, p_client_media_id, p_media_type, p_mime_type, p_extension,
    left(p_original_name, 255), p_source, p_declared_size, p_duration,
    format('service-requests/%s/%s/%s.%s', split_part(v_request.reference, '-', 2), v_request.reference, v_id, p_extension)
  )
  returning *;
end $$;

-- Marks a verified upload. Idempotent: an UPLOADED row is returned unchanged.
create function public.mark_service_media_uploaded(p_media_id uuid, p_file_size bigint)
returns setof public.service_media
language sql
security definer
set search_path = public
as $$
  update public.service_media
     set upload_status = 'UPLOADED', file_size = p_file_size, uploaded_at = now(), failure_reason = null
   where id = p_media_id and upload_status = 'PENDING';
  select * from public.service_media where id = p_media_id;
$$;

create function public.mark_service_media_failed(p_media_id uuid, p_reason text)
returns setof public.service_media
language sql
security definer
set search_path = public
as $$
  update public.service_media
     set upload_status = 'FAILED', failure_reason = left(p_reason, 200), file_size = null
   where id = p_media_id and upload_status = 'PENDING';
  select * from public.service_media where id = p_media_id;
$$;

revoke all on function public.reserve_service_media(uuid, uuid, public.service_media_type, text, text, bigint, text, text, numeric, integer, integer) from public, anon, authenticated;
revoke all on function public.mark_service_media_uploaded(uuid, bigint) from public, anon, authenticated;
revoke all on function public.mark_service_media_failed(uuid, text) from public, anon, authenticated;
grant execute on function public.reserve_service_media(uuid, uuid, public.service_media_type, text, text, bigint, text, text, numeric, integer, integer) to service_role;
grant execute on function public.mark_service_media_uploaded(uuid, bigint) to service_role;
grant execute on function public.mark_service_media_failed(uuid, text) to service_role;

-- ─── Private bucket ─────────────────────────────────────────────────────────
-- public = false: no public URLs. No storage.objects policies are created for
-- this bucket, so anon/authenticated can't list, read, write or delete; the
-- only ways in are the service role (server) and short-lived signed URLs it
-- issues. Storage itself enforces the size limit and MIME allow-list on every
-- upload. 50 MB is the Supabase Free plan's per-file ceiling (raise with Pro).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'service-evidence', 'service-evidence', false, 52428800,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif',
    'video/mp4', 'video/quicktime', 'video/webm', 'video/3gpp',
    'audio/webm', 'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/mpeg',
    'audio/ogg', 'audio/wav', 'audio/x-wav', 'audio/3gpp'
  ]
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
